import { fal } from "@fal-ai/client";

// Configure fal.ai client
fal.config({
    credentials: process.env.FAL_KEY,
});

// Veo 3.1 model endpoints
// Using fast variant for better pricing
// Ref: https://fal.ai/models/fal-ai/veo3.1/fast/image-to-video/api
const VEO_ENDPOINTS = {
    textToVideo: "fal-ai/veo3.1/fast",
    imageToVideo: "fal-ai/veo3.1/fast/image-to-video",
    extendVideo: "fal-ai/veo3.1/fast/extend-video",
} as const;

export interface VeoGenerateRequest {
    prompt: string;
    imageUrl?: string; // For image-to-video
    duration?: 5 | 8; // Veo supports 5-8 seconds
    aspectRatio?: "16:9" | "9:16" | "1:1";
    enableAudio?: boolean;
}

export interface VeoGenerateResult {
    videoUrl: string;
    duration: number;
    hasAudio: boolean;
    requestId: string;
}

/**
 * Generate video using Veo 3.1 via fal.ai
 * Supports both text-to-video and image-to-video
 */
export async function generateVeoVideo(
    request: VeoGenerateRequest
): Promise<VeoGenerateResult> {
    const { prompt, imageUrl, duration = 5, aspectRatio = "16:9", enableAudio = true } = request;

    // Choose endpoint based on whether we have an image
    const endpoint = imageUrl ? VEO_ENDPOINTS.imageToVideo : VEO_ENDPOINTS.textToVideo;

    console.log(`[fal.ai Veo 3.1] Starting generation:`, {
        endpoint,
        prompt: prompt.substring(0, 100) + '...',
        hasImage: !!imageUrl,
        duration,
        aspectRatio,
        enableAudio,
    });

    try {
        // Build input based on endpoint type
        // veo3.1/fast uses different parameter format
        const baseInput = {
            prompt,
            duration_seconds: duration, // number, not string
            aspect_ratio: aspectRatio,
        };

        const input = imageUrl
            ? { ...baseInput, image_url: imageUrl }
            : baseInput;

        console.log(`[fal.ai Veo 3.1] Input:`, JSON.stringify(input, null, 2));

        const result = await fal.subscribe(endpoint, {
            input: input as Parameters<typeof fal.subscribe>[1]["input"],
            logs: true,
            onQueueUpdate: (update) => {
                if (update.status === "IN_PROGRESS") {
                    console.log(`[fal.ai Veo 3.1] Progress:`, update.logs?.map(l => l.message).join(", "));
                }
            },
        });

        console.log(`[fal.ai Veo 3.1] Generation complete - Full response:`, JSON.stringify(result.data, null, 2));

        // Extract video URL from result - fal.ai veo3.1 returns video.url
        const data = result.data as { video?: { url: string }; url?: string };
        const videoUrl = data?.video?.url || data?.url;

        if (!videoUrl) {
            console.error(`[fal.ai Veo 3.1] No video URL found in response:`, result.data);
            throw new Error("No video URL in response");
        }

        console.log(`[fal.ai Veo 3.1] Video URL:`, videoUrl);

        return {
            videoUrl,
            duration,
            hasAudio: enableAudio,
            requestId: result.requestId,
        };
    } catch (error: unknown) {
        // Log full error details for debugging
        if (error && typeof error === 'object' && 'body' in error) {
            console.error(`[fal.ai Veo 3.1] Error body:`, JSON.stringify((error as { body: unknown }).body, null, 2));
        }
        console.error(`[fal.ai Veo 3.1] Error:`, error);
        throw error;
    }
}

/**
 * Calculate token cost for Veo 3.1 video generation
 * Premium tier with native audio - HIGH MARGIN TIER
 * 
 * fal.ai Veo cost: ~$0.45/5s, ~$0.72/8s with audio
 * 1 token = Rp 330, 1 USD = Rp 16.500
 * 
 * 5s: $0.45 = Rp 7.425, sell 250 token = Rp 82.500, margin 91%
 * 8s: $0.72 = Rp 11.880, sell 400 token = Rp 132.000, margin 91%
 */
export function getVeoCost(duration: 5 | 8 | 10): number {
    // Token costs based on duration - ANTI-BONCOS PRICING
    const costs: Record<number, number> = {
        5: 250,   // Premium 5s with audio
        8: 400,   // Premium 8s with audio
        10: 500,  // Premium 10s (if available)
    };

    return costs[duration] || 250;
}

/**
 * Check if fal.ai is configured
 */
export function isFalConfigured(): boolean {
    return !!process.env.FAL_KEY;
}

// ============================================
// Veo 3.1 Extend Video
// Ref: https://fal.ai/models/fal-ai/veo3.1/fast/extend-video/api
// ============================================

export interface VeoExtendRequest {
    videoUrl: string;
    prompt?: string;
    enableAudio?: boolean;
}

export interface VeoExtendResult {
    videoUrl: string;
    duration: number;
    hasAudio: boolean;
    requestId: string;
}

/**
 * Extend a Veo 3.1 video by 4 more seconds
 * Only works with videos generated by Veo 3.1
 */
export async function extendVeoVideo(
    request: VeoExtendRequest
): Promise<VeoExtendResult> {
    const { videoUrl, prompt = "", enableAudio = true } = request;

    console.log(`[fal.ai Veo 3.1 Extend] Starting extension:`, {
        endpoint: VEO_ENDPOINTS.extendVideo,
        videoUrl: videoUrl.substring(0, 50) + '...',
        prompt: prompt.substring(0, 100) + (prompt.length > 100 ? '...' : ''),
        enableAudio,
    });

    try {
        const input = {
            video_url: videoUrl,
            prompt: prompt || undefined,
            enable_audio: enableAudio,
        };

        console.log(`[fal.ai Veo 3.1 Extend] Input:`, JSON.stringify({
            ...input,
            video_url: input.video_url.substring(0, 50) + '...',
        }, null, 2));

        const result = await fal.subscribe(VEO_ENDPOINTS.extendVideo, {
            input: input as Parameters<typeof fal.subscribe>[1]["input"],
            logs: true,
            onQueueUpdate: (update) => {
                if (update.status === "IN_PROGRESS") {
                    console.log(`[fal.ai Veo 3.1 Extend] Progress:`, update.logs?.map(l => l.message).join(", "));
                }
            },
        });

        console.log(`[fal.ai Veo 3.1 Extend] Extension complete - Full response:`, JSON.stringify(result.data, null, 2));

        // Extract video URL from result
        const data = result.data as { video?: { url: string }; url?: string };
        const outputVideoUrl = data?.video?.url || data?.url;

        if (!outputVideoUrl) {
            console.error(`[fal.ai Veo 3.1 Extend] No video URL found in response:`, result.data);
            throw new Error("No video URL in response");
        }

        console.log(`[fal.ai Veo 3.1 Extend] Output URL:`, outputVideoUrl);

        return {
            videoUrl: outputVideoUrl,
            duration: 4, // Extension adds ~4 seconds
            hasAudio: enableAudio,
            requestId: result.requestId,
        };
    } catch (error: unknown) {
        if (error && typeof error === 'object' && 'body' in error) {
            console.error(`[fal.ai Veo 3.1 Extend] Error body:`, JSON.stringify((error as { body: unknown }).body, null, 2));
        }
        console.error(`[fal.ai Veo 3.1 Extend] Error:`, error);
        throw error;
    }
}

/**
 * Get token cost for Veo 3.1 video extension
 * Extension adds ~4 seconds to the video
 */
export function getVeoExtendCost(): number {
    return 200; // Fixed cost for extension (similar to 5s generation)
}

// ============================================
// GPT-Image-1.5 - Image Generation
// Ref: https://fal.ai/models/fal-ai/gpt-image-1.5/api
// ============================================

const IMAGE_ENDPOINT = "fal-ai/gpt-image-1.5" as const;

export interface ImageGenerateRequest {
    prompt: string;
    size?: "1024x1024" | "512x512" | "1024x1536" | "1536x1024";
    quality?: "low" | "medium" | "high";
    outputFormat?: "png" | "jpeg" | "webp";
}

export interface ImageGenerateResult {
    imageUrl: string;
    requestId: string;
}

/**
 * Generate image using GPT-Image-1.5 via fal.ai (Blocking/Sync)
 * Model: fal-ai/gpt-image-1.5
 */
export async function generateImage(
    request: ImageGenerateRequest
): Promise<ImageGenerateResult> {
    const {
        prompt,
        size = "1024x1024",
        quality = "high",
        outputFormat = "png"
    } = request;

    console.log(`[fal.ai GPT-Image-1.5] Starting generation:`, {
        endpoint: IMAGE_ENDPOINT,
        prompt: prompt.substring(0, 100) + (prompt.length > 100 ? '...' : ''),
        size,
        quality,
        outputFormat,
    });

    try {
        const input = {
            prompt,
            image_size: size,
            quality,
            output_format: outputFormat,
        };

        console.log(`[fal.ai GPT-Image-1.5] Input:`, JSON.stringify(input, null, 2));

        const result = await fal.subscribe(IMAGE_ENDPOINT, {
            input: input as Parameters<typeof fal.subscribe>[1]["input"],
            logs: true,
            onQueueUpdate: (update) => {
                if (update.status === "IN_PROGRESS") {
                    console.log(`[fal.ai GPT-Image-1.5] Progress:`, update.logs?.map(l => l.message).join(", "));
                }
            },
        });

        console.log(`[fal.ai GPT-Image-1.5] Generation complete - Full response:`, JSON.stringify(result.data, null, 2));

        // Extract image URL from result
        const data = result.data as {
            images?: Array<{ url: string }>;
            image?: { url: string };
            url?: string;
        };

        const imageUrl = data?.images?.[0]?.url || data?.image?.url || data?.url;

        if (!imageUrl) {
            console.error(`[fal.ai GPT-Image-1.5] No image URL found in response:`, result.data);
            throw new Error("No image URL in response");
        }

        console.log(`[fal.ai GPT-Image-1.5] Image URL:`, imageUrl);

        return {
            imageUrl,
            requestId: result.requestId,
        };
    } catch (error: unknown) {
        // Log full error details for debugging
        if (error && typeof error === 'object' && 'body' in error) {
            console.error(`[fal.ai GPT-Image-1.5] Error body:`, JSON.stringify((error as { body: unknown }).body, null, 2));
        }
        console.error(`[fal.ai GPT-Image-1.5] Error:`, error);
        throw error;
    }
}

/**
 * Submit image generation to Fal.ai queue (Async)
 * Returns request_id immediately to prevent serverless timeouts
 */
export async function submitImageGeneration(
    request: ImageGenerateRequest
): Promise<{ requestId: string }> {
    const {
        prompt,
        size = "1024x1024",
        quality = "high",
        outputFormat = "png"
    } = request;

    const input = {
        prompt,
        image_size: size,
        quality,
        output_format: outputFormat,
    };

    const { request_id } = await fal.queue.submit(IMAGE_ENDPOINT, {
        input,
        webhookUrl: undefined, // Implement webhook if needed later
    });

    return { requestId: request_id };
}

/**
 * Check status of image generation
 */
export async function checkImageGenerationStatus(requestId: string): Promise<{
    status: "IN_QUEUE" | "IN_PROGRESS" | "COMPLETED" | "FAILED";
    imageUrl?: string;
    error?: string;
}> {
    const status = await fal.queue.status(IMAGE_ENDPOINT, {
        requestId,
        logs: true
    });

    if (status.status === "COMPLETED") {
        const data = status.data as {
            images?: Array<{ url: string }>;
            image?: { url: string };
            url?: string;
        };
        const imageUrl = data?.images?.[0]?.url || data?.image?.url || data?.url;

        return {
            status: "COMPLETED",
            imageUrl,
        };
    }

    if (status.status === "FAILED") { // Note: 'FAILED' might not be the exact string from SDK, usually 'COMPLETED' with error or 'IN_PROGRESS'
        // Actually fal.queue.status returns { status: 'IN_QUEUE' | 'IN_PROGRESS' | 'COMPLETED' | 'OC_ERROR' | ... }
        // We'll treat checking logs or error field if needed.
        // But purely based on types, if it failed, it might throw or return generic error.
        return {
            status: "FAILED",
            error: "Generation failed"
        };
    }

    // Default return
    return {
        status: status.status as any
    };
}

// ============================================
// GPT-Image-1.5 Edit - Image Transformation
// Ref: https://fal.ai/models/fal-ai/gpt-image-1.5/edit/api
// ============================================

const IMAGE_EDIT_ENDPOINT = "fal-ai/gpt-image-1.5/edit" as const;

export interface ImageTransformRequest {
    imageUrl: string;
    prompt: string;
    size?: "1024x1024" | "512x512" | "1024x1536" | "1536x1024";
    quality?: "low" | "medium" | "high";
    outputFormat?: "png" | "jpeg" | "webp";
}

export interface ImageTransformResult {
    imageUrl: string;
    requestId: string;
}

/**
 * Transform/edit an image using GPT-Image-1.5 edit endpoint
 * This does whole-image transformation (no mask needed)
 */
export async function transformImage(
    request: ImageTransformRequest
): Promise<ImageTransformResult> {
    const {
        imageUrl,
        prompt,
        size = "1024x1024",
        quality = "high",
        outputFormat = "png"
    } = request;

    console.log(`[fal.ai GPT-Image-1.5 Edit] Starting transformation:`, {
        endpoint: IMAGE_EDIT_ENDPOINT,
        prompt: prompt.substring(0, 100) + (prompt.length > 100 ? '...' : ''),
        size,
        quality,
        outputFormat,
    });

    try {
        // Note: GPT-Image-1.5 Edit API requires `image_urls` (array), not `image_url`
        const input = {
            image_urls: [imageUrl], // Array of image URLs
            prompt,
            image_size: size,
            quality,
            output_format: outputFormat,
        };

        console.log(`[fal.ai GPT-Image-1.5 Edit] Input:`, JSON.stringify({
            ...input,
            image_urls: [input.image_urls[0].substring(0, 50) + '...'],
        }, null, 2));

        const result = await fal.subscribe(IMAGE_EDIT_ENDPOINT, {
            input: input as Parameters<typeof fal.subscribe>[1]["input"],
            logs: true,
            onQueueUpdate: (update) => {
                if (update.status === "IN_PROGRESS") {
                    console.log(`[fal.ai GPT-Image-1.5 Edit] Progress:`, update.logs?.map(l => l.message).join(", "));
                }
            },
        });

        console.log(`[fal.ai GPT-Image-1.5 Edit] Transform complete - Full response:`, JSON.stringify(result.data, null, 2));

        // Extract image URL from result
        const data = result.data as {
            images?: Array<{ url: string }>;
            image?: { url: string };
            url?: string;
        };

        const outputImageUrl = data?.images?.[0]?.url || data?.image?.url || data?.url;

        if (!outputImageUrl) {
            console.error(`[fal.ai GPT-Image-1.5 Edit] No image URL found in response:`, result.data);
            throw new Error("No image URL in response");
        }

        console.log(`[fal.ai GPT-Image-1.5 Edit] Output URL:`, outputImageUrl);

        return {
            imageUrl: outputImageUrl,
            requestId: result.requestId,
        };
    } catch (error: unknown) {
        if (error && typeof error === 'object' && 'body' in error) {
            console.error(`[fal.ai GPT-Image-1.5 Edit] Error body:`, JSON.stringify((error as { body: unknown }).body, null, 2));
        }
        console.error(`[fal.ai GPT-Image-1.5 Edit] Error:`, error);
        throw error;
    }
}

/**
 * Get token cost for image transformation
 */
export function getImageTransformCost(): number {
    return 25; // Fixed cost per transformation
}

export { fal };
