import { WAN_VIDEO_COSTS, type WanResolution } from "./fal-wan";
import OpenAI from "openai";

/**
 * Supported target durations for long video generation
 */
export type LongVideoDuration = 60 | 90 | 120;

/**
 * Generation mode for long video
 * - continuous: Segments connected via image-to-video from last frame (smoother transitions)
 * - different-angles: Each segment generated independently via text-to-video (more variety)
 */
export type LongVideoMode = "continuous" | "different-angles";

/**
 * Segment duration (using Wan 2.6 max duration)
 */
export const SEGMENT_DURATION = 15;

/**
 * Long video job status
 */
export type LongVideoStatus = "pending" | "processing" | "stitching" | "completed" | "failed";

/**
 * Long video job settings
 */
export interface LongVideoSettings {
    resolution: WanResolution;
    aspectRatio: "16:9" | "9:16" | "1:1";
    negativePrompt?: string;
    mode?: LongVideoMode;
}

/**
 * Long video segment info
 */
export interface LongVideoSegment {
    id: string;
    generationId: string;
    order: number;
    status: "pending" | "processing" | "completed" | "failed";
    duration: number;
    videoUrl?: string;
    thumbnailUrl?: string;
    createdAt: string;
}

/**
 * Long video job
 */
export interface LongVideoJob {
    id: string;
    userId: string;
    status: LongVideoStatus;
    prompt: string;
    targetDuration: LongVideoDuration;
    currentDuration: number;
    settings: LongVideoSettings;
    segments: LongVideoSegment[];
    finalVideoUrl?: string;
    tokensUsed: number;
    tokensReserved: number;
    error?: string;
    createdAt: string;
    updatedAt: string;
}

/**
 * Calculate number of segments needed for target duration
 */
export function getSegmentCount(targetDuration: LongVideoDuration): number {
    return Math.ceil(targetDuration / SEGMENT_DURATION);
}

/**
 * Get cost per segment based on resolution
 * Uses Wan 2.6 15s pricing
 */
export function getCostPerSegment(resolution: WanResolution): number {
    return WAN_VIDEO_COSTS[resolution][15];
}

/**
 * Calculate total token cost for long video
 */
export function getLongVideoCost(
    targetDuration: LongVideoDuration,
    resolution: WanResolution
): number {
    const segmentCount = getSegmentCount(targetDuration);
    const costPerSegment = getCostPerSegment(resolution);
    return segmentCount * costPerSegment;
}

/**
 * Get pricing breakdown for display
 */
export function getLongVideoPricing(
    targetDuration: LongVideoDuration,
    resolution: WanResolution
): {
    segmentCount: number;
    costPerSegment: number;
    totalCost: number;
    estimatedTimeMinutes: number;
} {
    const segmentCount = getSegmentCount(targetDuration);
    const costPerSegment = getCostPerSegment(resolution);
    const totalCost = segmentCount * costPerSegment;
    
    // Estimate ~2-3 minutes per segment for generation
    const estimatedTimeMinutes = segmentCount * 2.5;
    
    return {
        segmentCount,
        costPerSegment,
        totalCost,
        estimatedTimeMinutes,
    };
}

/**
 * Calculate progress percentage
 */
export function getProgressPercentage(
    currentDuration: number,
    targetDuration: LongVideoDuration
): number {
    return Math.min(100, Math.round((currentDuration / targetDuration) * 100));
}

/**
 * Get remaining segments count
 */
export function getRemainingSegments(
    completedSegments: number,
    targetDuration: LongVideoDuration
): number {
    const totalSegments = getSegmentCount(targetDuration);
    return Math.max(0, totalSegments - completedSegments);
}

/**
 * Check if job is ready for stitching
 */
export function isReadyForStitching(job: LongVideoJob): boolean {
    const requiredSegments = getSegmentCount(job.targetDuration);
    const completedSegments = job.segments.filter(s => s.status === "completed").length;
    return completedSegments >= requiredSegments;
}

/**
 * Get next segment order number
 */
export function getNextSegmentOrder(job: LongVideoJob): number {
    if (job.segments.length === 0) return 0;
    return Math.max(...job.segments.map(s => s.order)) + 1;
}

/**
 * Validate target duration
 */
export function isValidDuration(duration: number): duration is LongVideoDuration {
    return duration === 60 || duration === 90 || duration === 120;
}

/**
 * Format duration for display (e.g., "1:30" for 90 seconds)
 */
export function formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
}

/**
 * Get human-readable status
 */
export function getStatusLabel(status: LongVideoStatus): string {
    const labels: Record<LongVideoStatus, string> = {
        pending: "Menunggu",
        processing: "Sedang Diproses",
        stitching: "Menggabungkan Video",
        completed: "Selesai",
        failed: "Gagal",
    };
    return labels[status];
}

/**
 * Segment prompt generated by AI
 */
export interface SegmentPrompt {
    order: number;
    startTime: number;
    endTime: number;
    prompt: string;
    description?: string;
}

/**
 * Create OpenAI client for Sumopod
 */
function createSumopodClient(): OpenAI {
    const apiKey = process.env.SUMOPOD_API_KEY;
    const baseURL = process.env.SUMOPOD_BASE_URL || "https://ai.sumopod.com/v1";
    
    if (!apiKey) {
        throw new Error("SUMOPOD_API_KEY not configured");
    }
    
    return new OpenAI({ apiKey, baseURL });
}

/**
 * Generate per-segment prompts using AI
 * 
 * Takes a single user prompt and breaks it down into detailed,
 * cinematic prompts for each 15-second segment.
 * 
 * @param userPrompt - Original prompt from user
 * @param targetDuration - Target video duration (60, 90, or 120 seconds)
 * @param aspectRatio - Video aspect ratio for context
 * @returns Array of segment prompts
 */
export async function generateSegmentPrompts(
    userPrompt: string,
    targetDuration: LongVideoDuration,
    aspectRatio: "16:9" | "9:16" | "1:1" = "16:9"
): Promise<SegmentPrompt[]> {
    const segmentCount = getSegmentCount(targetDuration);
    
    console.log(`[LongVideo] Generating ${segmentCount} segment prompts for: "${userPrompt.slice(0, 50)}..."`);
    
    try {
        const client = createSumopodClient();
        
        const systemPrompt = `You are a professional video director and cinematographer. 
Your task is to break down a user's video concept into detailed per-segment prompts for AI video generation.

IMPORTANT RULES:
1. Each segment is exactly ${SEGMENT_DURATION} seconds long
2. Create exactly ${segmentCount} segments for a ${targetDuration}-second video
3. Each segment prompt should be detailed, cinematic, and self-contained
4. Include camera movements, lighting, mood, and visual details
5. Ensure visual continuity - each segment should flow naturally into the next
6. The aspect ratio is ${aspectRatio} - optimize compositions accordingly
7. First segment should be an establishing shot, last segment should be a satisfying conclusion
8. Keep prompts in the SAME LANGUAGE as the user's input

OUTPUT FORMAT (JSON array):
[
  {
    "order": 0,
    "startTime": 0,
    "endTime": ${SEGMENT_DURATION},
    "prompt": "detailed cinematic prompt for this segment",
    "description": "brief description of what happens"
  },
  ...
]`;

        const userMessage = `Break down this video concept into ${segmentCount} segments of ${SEGMENT_DURATION} seconds each:

"${userPrompt}"

Generate detailed, cinematic prompts for each segment that will create a cohesive ${targetDuration}-second video.`;

        const response = await client.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: userMessage },
            ],
            temperature: 0.7,
            response_format: { type: "json_object" },
        });

        const content = response.choices[0]?.message?.content;
        if (!content) {
            throw new Error("No response from AI");
        }

        const parsed = JSON.parse(content);
        const segments: SegmentPrompt[] = parsed.segments || parsed;
        
        // Validate and normalize segments
        if (!Array.isArray(segments) || segments.length !== segmentCount) {
            console.warn(`[LongVideo] AI returned ${Array.isArray(segments) ? segments.length : 0} segments, expected ${segmentCount}`);
            // Fall back to simple breakdown
            return generateFallbackPrompts(userPrompt, targetDuration);
        }
        
        // Ensure proper ordering and timing
        const normalizedSegments = segments.map((seg, idx) => ({
            order: idx,
            startTime: idx * SEGMENT_DURATION,
            endTime: (idx + 1) * SEGMENT_DURATION,
            prompt: seg.prompt || userPrompt,
            description: seg.description,
        }));
        
        console.log(`[LongVideo] Generated ${normalizedSegments.length} segment prompts successfully`);
        return normalizedSegments;
        
    } catch (error) {
        console.error("[LongVideo] AI prompt generation failed:", error);
        // Fall back to simple repeated prompt with cinematic modifiers
        return generateFallbackPrompts(userPrompt, targetDuration);
    }
}

/**
 * Generate fallback prompts when AI fails
 * Uses cinematic modifiers to add variety
 */
function generateFallbackPrompts(
    userPrompt: string,
    targetDuration: LongVideoDuration
): SegmentPrompt[] {
    const segmentCount = getSegmentCount(targetDuration);
    
    const cinematicModifiers = [
        "establishing shot, wide angle, cinematic opening",
        "medium shot, dynamic movement, building tension",
        "close-up details, intimate perspective",
        "tracking shot, smooth camera movement",
        "dramatic lighting, atmospheric mood",
        "dynamic action, peak moment",
        "wide shot, environmental context",
        "final shot, satisfying conclusion",
    ];
    
    const segments: SegmentPrompt[] = [];
    
    for (let i = 0; i < segmentCount; i++) {
        const modifier = cinematicModifiers[i % cinematicModifiers.length];
        segments.push({
            order: i,
            startTime: i * SEGMENT_DURATION,
            endTime: (i + 1) * SEGMENT_DURATION,
            prompt: `${userPrompt}, ${modifier}`,
            description: `Segment ${i + 1}: ${modifier}`,
        });
    }
    
    console.log(`[LongVideo] Generated ${segments.length} fallback prompts`);
    return segments;
}

/**
 * Get prompt for a specific segment
 * Used when continuing video generation
 */
export function getSegmentPrompt(
    segmentPrompts: SegmentPrompt[],
    segmentOrder: number,
    fallbackPrompt: string
): string {
    const segment = segmentPrompts.find(s => s.order === segmentOrder);
    return segment?.prompt || fallbackPrompt;
}
