import { createAdminClient } from "@/lib/supabase/server";
import { withTimeout, withRetry, TIMEOUTS, RETRY_CONFIGS } from "./api-utils";
import { validateUrl } from "./url-validator";

/**
 * Storage Utilities
 *
 * Functions for persisting external media (images/videos) to Supabase Storage.
 * Includes timeout protection and retry mechanisms for reliability.
 */

// Maximum file sizes
const MAX_IMAGE_SIZE = 10 * 1024 * 1024; // 10MB
const MAX_VIDEO_SIZE = 100 * 1024 * 1024; // 100MB

/**
 * Fetch external file with timeout and size validation
 */
async function fetchExternalFile(
    url: string,
    maxSize: number,
    timeoutMs: number
): Promise<Buffer> {
    // Validate URL (basic security check)
    const validation = validateUrl(url);
    if (!validation.valid) {
        throw new Error(`Invalid URL: ${validation.error}`);
    }

    // Fetch with timeout
    const response = await withTimeout(
        fetch(url),
        timeoutMs,
        `Fetch timed out after ${timeoutMs}ms`
    );

    if (!response.ok) {
        throw new Error(`Failed to fetch: ${response.status} ${response.statusText}`);
    }

    // Check content length before downloading
    const contentLength = response.headers.get("content-length");
    if (contentLength && parseInt(contentLength) > maxSize) {
        throw new Error(`File too large: ${contentLength} bytes exceeds ${maxSize} byte limit`);
    }

    const arrayBuffer = await response.arrayBuffer();

    // Verify actual size
    if (arrayBuffer.byteLength > maxSize) {
        throw new Error(`File too large: ${arrayBuffer.byteLength} bytes exceeds ${maxSize} byte limit`);
    }

    return Buffer.from(arrayBuffer);
}

/**
 * Upload buffer to Supabase Storage with retry
 */
async function uploadToStorage(
    buffer: Buffer,
    filename: string,
    contentType: string
): Promise<string> {
    const adminClient = createAdminClient();

    const uploadFn = async () => {
        const { error } = await adminClient
            .storage
            .from("generations")
            .upload(filename, buffer, {
                contentType,
                upsert: false,
            });

        if (error) {
            console.error("[Storage] Upload error:", error);
            throw new Error(`Storage upload failed: ${error.message}`);
        }

        const { data: { publicUrl } } = adminClient
            .storage
            .from("generations")
            .getPublicUrl(filename);

        return publicUrl;
    };

    // Retry upload on failure
    return withRetry(uploadFn, {
        ...RETRY_CONFIGS.STANDARD,
        onRetry: (error, attempt) => {
            console.log(`[Storage] Upload retry ${attempt}: ${error.message}`);
        },
    });
}

/**
 * Generate unique filename for storage
 */
function generateFilename(userId: string, prefix: string, extension: string): string {
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 10000).toString().padStart(4, "0");
    return `${userId}/${prefix}-${timestamp}-${random}.${extension}`;
}

/**
 * Downloads an image from a URL and uploads it to Supabase Storage permanently.
 * Useful for saving images generated by AI (which have expiring URLs).
 *
 * @param externalUrl - URL of the image to download
 * @param userId - User ID for organizing files
 * @returns Public URL of the persisted image
 */
export async function persistExternalImage(
    externalUrl: string,
    userId: string
): Promise<string> {
    console.log(`[Storage] Persisting image for user ${userId.slice(0, 8)}...`);

    // Download with timeout (30 seconds for images)
    const buffer = await fetchExternalFile(
        externalUrl,
        MAX_IMAGE_SIZE,
        TIMEOUTS.LONG
    );

    // Upload to storage
    const filename = generateFilename(userId, "gen", "png");
    const publicUrl = await uploadToStorage(buffer, filename, "image/png");

    console.log(`[Storage] Image persisted: ${filename}`);
    return publicUrl;
}

/**
 * Persists a base64/data URL image directly to storage.
 *
 * @param dataUrl - Base64 data URL of the image
 * @param userId - User ID for organizing files
 * @returns Public URL of the persisted image
 */
export async function persistBase64Image(
    dataUrl: string,
    userId: string
): Promise<string> {
    console.log(`[Storage] Persisting base64 image for user ${userId.slice(0, 8)}...`);

    // Extract base64 data
    const base64Data = dataUrl.replace(/^data:image\/\w+;base64,/, "");
    const buffer = Buffer.from(base64Data, "base64");

    // Check size
    if (buffer.byteLength > MAX_IMAGE_SIZE) {
        throw new Error(`Image too large: ${buffer.byteLength} bytes`);
    }

    // Upload to storage
    const filename = generateFilename(userId, "save", "png");
    const publicUrl = await uploadToStorage(buffer, filename, "image/png");

    console.log(`[Storage] Base64 image persisted: ${filename}`);
    return publicUrl;
}

/**
 * Downloads a video from a URL and uploads it to Supabase Storage permanently.
 * Useful for saving videos generated by Kling AI (which have expiring URLs).
 *
 * @param externalUrl - URL of the video to download
 * @param userId - User ID for organizing files
 * @returns Public URL of the persisted video
 */
export async function persistExternalVideo(
    externalUrl: string,
    userId: string
): Promise<string> {
    console.log(`[Storage] Persisting video for user ${userId.slice(0, 8)}...`);

    // Download with longer timeout (60 seconds for videos)
    const buffer = await fetchExternalFile(
        externalUrl,
        MAX_VIDEO_SIZE,
        TIMEOUTS.EXTRA_LONG
    );

    // Upload to storage
    const filename = generateFilename(userId, "video", "mp4");
    const publicUrl = await uploadToStorage(buffer, filename, "video/mp4");

    console.log(`[Storage] Video persisted: ${filename} (${buffer.byteLength} bytes)`);
    return publicUrl;
}

/**
 * Delete a file from storage
 * Useful for cleanup or when generation fails
 */
export async function deleteFromStorage(filePath: string): Promise<void> {
    const adminClient = createAdminClient();

    const { error } = await adminClient
        .storage
        .from("generations")
        .remove([filePath]);

    if (error) {
        console.error(`[Storage] Delete failed for ${filePath}:`, error);
        throw new Error(`Failed to delete file: ${error.message}`);
    }

    console.log(`[Storage] Deleted: ${filePath}`);
}

/**
 * Check if a file exists in storage
 */
export async function fileExistsInStorage(filePath: string): Promise<boolean> {
    const adminClient = createAdminClient();

    const { data, error } = await adminClient
        .storage
        .from("generations")
        .list(filePath.split("/").slice(0, -1).join("/"), {
            search: filePath.split("/").pop(),
        });

    if (error) {
        return false;
    }

    return data.length > 0;
}
