import { createAdminClient } from "./supabase/server";

/**
 * Downloads an image from a URL and uploads it to Supabase Storage permanently.
 * Useful for saving images generated by AI (which have expiring URLs).
 */
export async function persistExternalImage(externalUrl: string, userId: string): Promise<string> {
    const adminClient = createAdminClient();

    // 1. Download image
    const response = await fetch(externalUrl);
    if (!response.ok) throw new Error(`Failed to fetch external image: ${response.statusText}`);

    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // 2. Generate filename
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1000);
    const filename = `${userId}/gen-${timestamp}-${random}.png`;

    // 3. Upload to 'generations' bucket
    const { data, error } = await adminClient
        .storage
        .from('generations')
        .upload(filename, buffer, {
            contentType: 'image/png',
            upsert: false
        });

    if (error) {
        console.error("Storage upload error:", error);
        throw new Error("Failed to persist image to storage");
    }

    // 4. Get Public URL
    const { data: { publicUrl } } = adminClient
        .storage
        .from('generations')
        .getPublicUrl(filename);

    return publicUrl;
}

/**
 * Persists a base64/data URL image directly to storage.
 */
export async function persistBase64Image(dataUrl: string, userId: string): Promise<string> {
    const adminClient = createAdminClient();

    const base64Data = dataUrl.replace(/^data:image\/\w+;base64,/, "");
    const buffer = Buffer.from(base64Data, 'base64');

    const filename = `${userId}/save-${Date.now()}.png`;

    const { error } = await adminClient
        .storage
        .from('generations')
        .upload(filename, buffer, {
            contentType: 'image/png',
            upsert: false
        });

    if (error) {
        console.error("Storage upload error:", error);
        throw new Error("Failed to persist base64 image to storage");
    }

    const { data: { publicUrl } } = adminClient
        .storage
        .from('generations')
        .getPublicUrl(filename);

    return publicUrl;
}
