-- Migration: Add segment_prompts column for AI-generated prompts
-- Stores per-segment prompts generated by AI for long video jobs

ALTER TABLE long_video_jobs 
ADD COLUMN IF NOT EXISTS segment_prompts JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN long_video_jobs.segment_prompts IS 'AI-generated prompts for each video segment';
